# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be2395078d36b55e7a4508a96bb38f4383d1e21c45793979aaa196b880f08e2d06df587eff1e878b625e661d4b097ca564fec25198618dc7a73b07a6692b965

test:
  secret_key_base: a670522e5744d28bec32f1d7402186e89071dcfbd660b4d6cc1b54440f4035e3c97dc310063f69bf841807dac0b6b56b1486ff5190d05301603ff9a942424074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
